title: Stockinsights Docs
description: Developers documentation at stockinsights
theme: just-the-docs

url: https://stockinsights-ai.github.io

favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

